### ISSUE TITLE
compile error!

### ISSUE THREAD

**Issue by zhangfq-chemistry** [colinw7/CQTty#2]
CEscapeColors.h:5:10: fatal error: CRGBA.h: No such file or directory

**Comment by colinw7** [comment]
Did you try the build script (scripts/build.sh) from the README which pulls in all required dependencies ?

**Comment by zhangfq-chemistry** [comment]
--- Build CQUtil ---
make: Nothing to be done for 'first'.
--- Build CImageLib ---
--- Build CFont ---
--- Build CVFont ---
make: Nothing to be done for 'all'.
--- Build CConfig ---
--- Build CFileUtil ---
--- Build CFile ---
--- Build CMath ---
--- Build CRegExp ---
g++ -c CRegExp.cpp -o ../obj/CRegExp.o -std=c++17 -I../include -I../../CStrUtil/include
CRegExp.cpp:9:10: fatal error: tre/regex.h: No such file or directory
    9 | #include <tre/regex.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:33: ../obj/CRegExp.o] Error 1
--- Build CStrUtil ---
--- Build CRGBName ---
make: Nothing to be done for 'all'.
--- Build COS ---
--- Build CUtil ---
--- Build CQTty (src) ---
g++  -o ../bin/CQTty ../obj/CEscapeColors.o ../obj/CEscape.o ../obj/CEscapeHandler.o ../obj/CEscapeParse.o ../obj/CLogFile.o ../obj/CPageText.o ../obj/CPageTextEscapeNotifier.o ../obj/CPageTextLine.o ../obj/CQPageText4014.o ../obj/CQPageTextButton.o ../obj/CQPageTextCanvas.o ../obj/CQPageText.o ../obj/CQPageTextState.o ../obj/CQPageTextStatus.o ../obj/CQPageTextToolBar.o ../obj/CQPageTextWidget.o ../obj/CQPageTextError.o ../obj/CQTty.o ../obj/CTextCell.o ../obj/CTty.o ../obj/main.o ../obj/moc_CQPageText4014.o ../obj/moc_CQPageTextButton.o ../obj/moc_CQPageTextCanvas.o ../obj/moc_CQPageText.o ../obj/moc_CQPageTextState.o ../obj/moc_CQPageTextStatus.o ../obj/moc_CQPageTextToolBar.o ../obj/moc_CQPageTextWidget.o ../obj/moc_CQPageTextError.o ../obj/moc_CQTty.o   -L../lib -L../../CQUtil/lib -L../../CImageLib/lib -L../../CFont/lib -L../../CVFont/lib -L../../CConfig/lib -L../../CFileUtil/lib -L../../CFile/lib -L../../CMath/lib -L../../CRegExp/lib -L../../CStrUtil/lib -L../../CRGBName/lib -L../../COS/lib -L../../CUtil/lib -lCQUtil -lCImageLib -lCFont -lCVFont -lCConfig -lCFileUtil -lCFile -lCMath -lCRGBName -lCRegExp -lCStrUtil -lCUtil -lCOS -ljpeg -lpng -ltre -lcurses /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread
/usr/bin/ld: cannot find -lCRegExp: No such file or directory
/usr/bin/ld: cannot find -ltre: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [Makefile:258: ../bin/CQTty] Error 1

**Comment by colinw7** [comment]
You need libtre-dev package installed. I'm using libtre-dev 0.8.0-6
